name: Gerar APK Android

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Gerar APK
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Dar permissão ao Gradle
        run: chmod +x ./gradlew

      - name: Gerar APK Debug
        run: ./gradlew assembleDebug

      - name: Enviar APK como arquivo
        uses: actions/upload-artifact@v4
        with:
          name: Mercadinho-Oliveira-APK
          path: app/build/outputs/apk/debug/*.apk
